---

name: Gather Pull Request Metadata
description: Gather useful publicly available information about Pull Request and provided in easy to digest JSON format.

branding:
  icon: box
  color: blue

author: Jan Macků <jamacku@redhat.com>

inputs:
  metadata-file-name:
    required: false
    default: pr-metadata.json
    description: Name of file where Pull Request metadata will be saved.
  token:
    required: true
    default: ${{ github.token }}
    description: GitHub token used to set issue labels.

outputs:
  metadata:
    description: Pull Request metadata in JSON format. Use fromJSON() to parse string back to JSON.
  metadata-file:
    description: Path to file containing Pull Request metadata in JSON format. Useful when uploading as artifact.

runs:
  using: 'node16'
  main: 'dist/index.js'

...
