---

name: Gather Pull Request Metadata
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  gather-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - id: Metadata
        name: Gather Pull Request Metadata
        uses: ./

      - name: Log Pull Request Metadata
        run: |
          echo "::warning::${{ steps.Metadata.outputs.metadata }}"

      - name: Upload artifact with gathered metadata
        uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05
        with:
          name: Pull Request Metadata
          path: ${{ steps.Metadata.outputs.metadata-file }}

...
