---

name: Gather Pull Request Metadata
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  gather-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222

      - id: Metadata
        name: Gather Pull Request Metadata
        uses: ./

      - name: Log Pull Request Metadata
        env:
          PR_METADATA: ${{ toJson(steps.Metadata.outputs.metadata) }}
        run: |
          echo -e "::warning::$PR_METADATA"

      - name: Upload artifact with gathered metadata
        uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05
        with:
          name: Pull Request Metadata
          path: ${{ steps.Metadata.outputs.metadata-file }}

...
