name: Publish package

on:
  release:
    types: [ created ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: yarn install

      - name: Compile
        run: yarn build

      - name: Test
        run: yarn test

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
